# Generated by Django 2.2.6 on 2019-10-13 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=7)),
                ('previsao_custo', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('excluido', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CentroLucro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=7)),
                ('excluido', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('banco', models.IntegerField()),
                ('tipo_conta', models.IntegerField()),
                ('titular', models.CharField(max_length=200)),
                ('cnpj_cpf_titular', models.CharField(max_length=14)),
                ('agencia', models.CharField(max_length=50)),
                ('conta', models.CharField(max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('excluido', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancariaMovimentacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo_movimentacao', models.IntegerField()),
                ('data_movimentacao', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('observacao', models.TextField(null=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.ContaBancaria')),
            ],
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('parcela_atual', models.IntegerField()),
                ('quantidade_parcelas', models.IntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('data_vencimento', models.DateTimeField(null=True)),
                ('pago', models.BooleanField()),
                ('data_pagamento', models.DateTimeField(null=True)),
                ('observacao', models.TextField(null=True)),
                ('data_cadastro', models.DateTimeField()),
                ('ordem', models.IntegerField()),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.CentroCusto')),
                ('conta_bancaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.ContaBancaria')),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('parcela_atual', models.IntegerField()),
                ('quantidade_parcelas', models.IntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('previsao_recebimento', models.DateTimeField(null=True)),
                ('observacao', models.TextField(null=True)),
                ('grupo_referencia', models.UUIDField(default=uuid.uuid4)),
                ('recebido', models.BooleanField(null=True)),
                ('data_recebimento', models.DateTimeField(null=True)),
                ('data_cadastro', models.DateTimeField()),
                ('ordem', models.IntegerField()),
                ('centro_lucro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.CentroLucro')),
                ('conta_bancaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.ContaBancaria')),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceberAnexo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=200)),
                ('observacao', models.TextField(null=True)),
                ('data_envio', models.DateTimeField()),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.ContaReceber')),
            ],
        ),
        migrations.CreateModel(
            name='ContaPagarAnexo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nnome_arquivo', models.CharField(max_length=200, null=True)),
                ('observacao', models.TextField(null=True)),
                ('data_envio', models.DateTimeField()),
                ('conta_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.ContaPagar')),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancariaMovimentacaoAnexo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=200, null=True)),
                ('observacao', models.TextField(null=True)),
                ('data_envio', models.DateTimeField()),
                ('conta_bancaria_movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.ContaBancariaMovimentacao')),
            ],
        ),
        migrations.CreateModel(
            name='CentroCustoPrevisao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('previsao_custo', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.CentroCusto')),
            ],
        ),
    ]
