# Generated by Django 2.2.6 on 2019-10-28 01:01

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=7)),
                ('previsao_custo', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('excluido', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CentroLucro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('cor', colorfield.fields.ColorField(max_length=18)),
                ('excluido', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('previsao_recebimento', models.DateTimeField()),
                ('observacao', models.TextField(null=True)),
                ('recebido', models.BooleanField(default=False)),
                ('data_recebimento', models.DateTimeField(null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('centro_lucro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.CentroLucro')),
            ],
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('data_vencimento', models.DateTimeField(null=True)),
                ('pago', models.BooleanField()),
                ('data_pagamento', models.DateTimeField(null=True)),
                ('observacao', models.TextField(null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.CentroCusto')),
            ],
        ),
    ]
