# Generated by Django 2.2.6 on 2019-10-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='previsao_recebimento',
            field=models.DateTimeField(default='2019-01-02 00:00:00'),
            preserve_default=False,
        ),
    ]
