# Generated by Django 2.2.6 on 2019-10-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancariamovimentacao',
            name='conta_bancaria',
        ),
        migrations.RemoveField(
            model_name='contabancariamovimentacaoanexo',
            name='conta_bancaria_movimentacao',
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='conta_bancaria',
        ),
        migrations.RemoveField(
            model_name='contareceber',
            name='centro_lucro',
        ),
        migrations.RemoveField(
            model_name='contareceber',
            name='conta_bancaria',
        ),
        migrations.RemoveField(
            model_name='contareceber',
            name='grupo_referencia',
        ),
        migrations.RemoveField(
            model_name='contareceber',
            name='quantidade_parcelas',
        ),
        migrations.RemoveField(
            model_name='contareceber',
            name='valor_total',
        ),
        migrations.DeleteModel(
            name='ContaBancaria',
        ),
        migrations.DeleteModel(
            name='ContaBancariaMovimentacao',
        ),
        migrations.DeleteModel(
            name='ContaBancariaMovimentacaoAnexo',
        ),
    ]
