# Generated by Django 2.2.6 on 2019-10-13 17:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20191013_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrolucro',
            name='cor',
            field=colorfield.fields.ColorField(max_length=18),
        ),
    ]
